name: Github Pages Astro CI

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x.x
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        shell: "bash"
        run: pnpm install

      - name: Build
        shell: "bash"
        env:
          PACKAGE_MANAGER: ${{ steps.lockfile.outputs.PACKAGE_MANAGER }}
        run: pnpm exec nx run my-site:build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "apps/my-site/dist/"

  deploy:
    needs: main
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
